name: flutter_with_clean_architecture
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^2.0.1
  flutter_bloc: ^0.21.0
  equatable: ^0.4.0
  dartz: ^0.8.6
  connectivity: ^0.4.3+7
  http: ^0.12.0+2
  shared_preferences: ^0.5.3+4
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true